// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://frogecmfyypfnuugadey.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZyb2dlY21meXlwZm51dWdhZGV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3ODUxMjQsImV4cCI6MjA2NDM2MTEyNH0.Hp1CzrJDu4FAa8dibZxGDtlPrb0YM3NBlVAenk-ZoU8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);